-- Cria sequências para as tabelas principais
-- O START WITH deve ser 1 número ACIMA do maior ID que inseriste manualmente.

CREATE SEQUENCE seq_anunciante
  START WITH 1000006
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE seq_agencia
  START WITH 2000006
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE seq_espaco
  START WITH 3000006
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE seq_publico_alvo
  START WITH 4000006
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE seq_processo
  START WITH 6000011
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE seq_peca_criativa
  START WITH 7000011
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE seq_campanha
  START WITH 8000006
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE seq_pagamento
  START WITH 5000006
  INCREMENT BY 1
  NOCACHE;